# -*- coding: utf-8 -*-
"""Wine Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6-d60Dp6EQJl_mYkMXkx8InncEg5z8n
"""

# retrieval.py
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

import pickle
import os

class WineRetriever:
    def __init__(self, csv_path, embeddings_path="wine_embeddings.pkl", force_recompute=False):
        self.df = pd.read_csv(csv_path)
        self.model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

        # Пробуем загрузить существующие эмбеддинги
        if os.path.exists(embeddings_path) and not force_recompute:
            print("🔄 Загружаем существующие эмбеддинги...")
            with open(embeddings_path, 'rb') as f:
                saved_data = pickle.load(f)
                self.wine_embeddings = saved_data['embeddings']
                self.wine_descriptions = saved_data['descriptions']
            print(f"✅ Загружено {len(self.wine_embeddings)} эмбеддингов")
        else:
            # Создаем новые эмбеддинги
            print("🔄 Создаем эмбеддинги для вин...")
            self.wine_descriptions = self._create_wine_descriptions()
            self.wine_embeddings = self.model.encode(self.wine_descriptions, show_progress_bar=True)

            # Сохраняем для будущего использования
            saved_data = {
                'embeddings': self.wine_embeddings,
                'descriptions': self.wine_descriptions
            }
            with open(embeddings_path, 'wb') as f:
                pickle.dump(saved_data, f)
            print(f"✅ Создано и сохранено {len(self.wine_embeddings)} эмбеддингов в {embeddings_path}")

    def _create_wine_descriptions(self):
        """Создаем текстовые описания из ваших колонок"""
        descriptions = []
        for _, row in self.df.iterrows():
            desc_parts = []

            # Используем доступные колонки


            if pd.notna(row.get('country')) and row.get('country'):
                desc_parts.append(f"Country: {row['country']}")

            if pd.notna(row.get('designation')) and row.get('designation'):
                desc_parts.append(f"Designation: {row['designation']}")

            if pd.notna(row.get('price')) and row.get('price'):
                desc_parts.append(f"Price: ${row['price']}")

            if pd.notna(row.get('province')) and row.get('province'):
                desc_parts.append(f"Province: {row['province']}")

            if pd.notna(row.get('region_1')) and row.get('region_1'):
                desc_parts.append(f"Region: {row['region_1']}")

            if pd.notna(row.get('region_2')) and row.get('region_2'):
                desc_parts.append(f"Subregion: {row['region_2']}")

            if pd.notna(row.get('title')) and row.get('title'):
                desc_parts.append(f"Title: {row['title']}")

            if pd.notna(row.get('variety')) and row.get('variety'):
                desc_parts.append(f"Grape variety: {row['variety']}")

            if pd.notna(row.get('winery')) and row.get('winery'):
                desc_parts.append(f"Winery: {row['winery']}")

            # Wine characteristics
            if pd.notna(row.get('flavor_profile')) and row.get('flavor_profile'):
                desc_parts.append(f"Flavor profile: {row['flavor_profile']}")

            if pd.notna(row.get('aroma')) and row.get('aroma'):
                desc_parts.append(f"Aroma: {row['aroma']}")

            if pd.notna(row.get('sweetness')) and row.get('sweetness'):
                desc_parts.append(f"Sweetness: {row['sweetness']}")

            if pd.notna(row.get('body')) and row.get('body'):
                desc_parts.append(f"Body: {row['body']}")

            if pd.notna(row.get('tannins')) and row.get('tannins'):
                desc_parts.append(f"Tannins: {row['tannins']}")

            if pd.notna(row.get('acidity')) and row.get('acidity'):
                desc_parts.append(f"Acidity: {row['acidity']}")

            if pd.notna(row.get('pairing_suggestions')) and row.get('pairing_suggestions'):
                desc_parts.append(f"Pairing suggestions: {row['pairing_suggestions']}")

            if pd.notna(row.get('mood')) and row.get('mood'):
                desc_parts.append(f"Mood: {row['mood']}")

            if pd.notna(row.get('aging_potential')) and row.get('aging_potential'):
                desc_parts.append(f"Aging potential: {row['aging_potential']}")

            if pd.notna(row.get('complexity')) and row.get('complexity'):
                desc_parts.append(f"Complexity: {row['complexity']}")

            if pd.notna(row.get('intensity')) and row.get('intensity'):
                desc_parts.append(f"Intensity: {row['intensity']}")

            if pd.notna(row.get('finish')) and row.get('finish'):
                desc_parts.append(f"Finish: {row['finish']}")

            description = ". ".join(desc_parts)
            descriptions.append(description)

        return descriptions

    def retrieve(self, user_query, top_k=20):
        """Векторный поиск по запросу пользователя"""
        query_embedding = self.model.encode([user_query])[0]

        # Косинусная схожесть
        similarities = cosine_similarity([query_embedding], self.wine_embeddings)[0]

        top_indices = np.argsort(similarities)[::-1][:top_k]

        retrieved_wines = []
        for idx in top_indices:
            wine_data = self.df.iloc[idx].to_dict()
            wine_data['similarity_score'] = float(similarities[idx])
            retrieved_wines.append(wine_data)

        # Сортируем по схожести
        retrieved_wines.sort(key=lambda x: x['similarity_score'], reverse=True)

        return retrieved_wines

    def search_by_filters(self, query=None, variety=None, country=None, max_price=None, top_k=10):
        """Гибридный поиск: семантический + фильтры"""
        if query:
            # Семантический поиск
            all_results = self.retrieve(query, top_k=50)
        else:
            # Если нет запроса, берем все вина
            all_results = [self.df.iloc[i].to_dict() for i in range(len(self.df))]
            for result in all_results:
                result['similarity_score'] = 0.5  # нейтральный скор

        # Применяем фильтры
        filtered_results = []
        for wine in all_results:
            if variety and pd.notna(wine.get('variety')):
                if variety.lower() not in str(wine['variety']).lower():
                    continue

            if country and pd.notna(wine.get('country')):
                if country.lower() not in str(wine['country']).lower():
                    continue

            if max_price and pd.notna(wine.get('price')):
                if wine['price'] > max_price:
                    continue

            filtered_results.append(wine)

        return filtered_results[:top_k]

# Ячейка 3: Первый запуск (сохранит эмбеддинги)
print("🚀 Первый запуск - создаем и сохраняем эмбеддинги...")
retriever = WineRetriever("final_wine_analysis_dataset.csv", embeddings_path="my_wine_embeddings.pkl")

import os
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

model_name = "microsoft/Phi-3.5-mini-instruct"

# Загрузка токенизатора
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Загрузка модели
# device_map="cuda" автоматически переместит модель на доступный GPU


# Загрузка модели с trust_remote_code=False
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=False # <-- ИЗМЕНИТЕ ЗДЕСЬ
)

# Сначала создадим пайплайн для генерации текста
phi_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device_map="cuda",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

def generate_explanation(query, wine, similarity_score):
    """Генерирует объяснение почему вино подходит под запрос"""

    prompt = f"""
You're an expert sommelier. Tell the user why this wine is perfect for his request.

User request: "{query}"

Wie info:
- Title: {wine.get('title', 'Не указано')}
- Variety: {wine.get('variety', 'Не указан')}
- Coutry: {wine.get('country', 'Не указана')}
- Region: {wine.get('region_1', 'Не указан')}
- Winary: {wine.get('winery', 'Не указана')}
- Price: ${wine.get('price', 'Не указана')}
- Description: {wine.get('description', 'Описание отсутствует')}
- Similarity: {similarity_score:.3f}

explanation (2-3 sentences, in english):
"""

    try:
        response = phi_pipeline(
            prompt,
            max_new_tokens=150,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

        explanation = response[0]['generated_text'].replace(prompt, "").strip()
        return explanation

    except Exception as e:
        return f"Не удалось сгенерировать объяснение: {e}"

def format_long_text(text, width=70):
    """Форматирует длинный текст с переносами строк"""
    import textwrap
    return '\n   '.join(textwrap.wrap(text, width=width))

# Обновленная функция вывода результатов
def print_recommendations_with_explanations(query, results, retriever):
    """Печатает рекомендации с LLM-объяснениями"""

    print(f"🔍 Results for: '{query}'\n")
    print("=" * 80)

    for i, wine in enumerate(results, 1):
        print(f"\n{i}. 🍷 {wine.get('title', 'Без названия')}")
        print(f"   📍 Variety: {wine.get('variety', 'N/A')}")
        print(f"   🌍 Country: {wine.get('country', 'N/A')}")
        print(f"   💰 Price: ${wine.get('price', 'N/A')}")
        print(f"   ⭐ Similarity: {wine['similarity_score']:.3f}")

        # Генерируем и показываем объяснение
        print(f"\n   💡 Explanation:")
        explanation = generate_explanation(query, wine, wine['similarity_score'])

        # Форматируем объяснение с переносами
        formatted_explanation = format_long_text(explanation)
        print(f"   {formatted_explanation}")

        print("\n" + "-" * 80)

query = "rich red wine with notes of cherry and chocolate"
results = retriever.retrieve(query, top_k=5)
print_recommendations_with_explanations(query, results, retriever)

def generate_filtered_explanation(query, wine, filters):
    """Generate LLM explanation for filtered recommendations"""

    prompt = f"""
You are a wine expert. Explain why this wine matches the user's specific criteria.

USER QUERY: "{query}"

FILTERS APPLIED:
- Variety: {filters.get('variety', 'Any')}
- Country: {filters.get('country', 'Any')}
- Max Price: ${filters.get('max_price', 'Any')}

WINE INFORMATION:
- Title: {wine.get('title', 'Not specified')}
- Variety: {wine.get('variety', 'Not specified')}
- Country: {wine.get('country', 'Not specified')}
- Region: {wine.get('region_1', 'Not specified')}
- Price: ${wine.get('price', 'Not specified')}
- Description: {wine.get('description', 'No description available')}
- Similarity Score: {wine.get('similarity_score', 0):.3f}

EXPLANATION (2-3 sentences in English):
Explain specifically how this wine matches both the semantic query AND the applied filters:
"""

    try:
        response = phi_pipeline(
            prompt,
            max_new_tokens=150,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

        explanation = response[0]['generated_text'].replace(prompt, "").strip()
        return explanation

    except Exception as e:
        return f"Could not generate explanation: {e}"

def print_filtered_recommendations_with_explanations(query, filtered_results, filters):
    """Print filtered results with LLM explanations"""

    print("🎯 Results with filters:")
    print(f"🔍 Query: '{query}'")
    print(f"📋 Filters: Variety={filters.get('variety', 'Any')}, "
          f"Country={filters.get('country', 'Any')}, "
          f"Max Price=${filters.get('max_price', 'Any')}")
    print("=" * 80)

    for i, wine in enumerate(filtered_results, 1):
        print(f"\n{i}. 🍷 {wine.get('title', 'No title')}")
        print(f"   📍 Variety: {wine.get('variety', 'N/A')}")
        print(f"   🌍 Country: {wine.get('country', 'N/A')} - {wine.get('region_1', 'N/A')}")
        print(f"   💰 Price: ${wine.get('price', 'N/A')}")
        print(f"   ⭐ Similarity: {wine['similarity_score']:.3f}")

        # Generate and display LLM explanation
        print(f"\n   💡 Why this matches your criteria:")
        explanation = generate_filtered_explanation(query, wine, filters)

        # Format text with proper wrapping
        import textwrap
        wrapped_text = textwrap.fill(explanation, width=70, initial_indent='   ', subsequent_indent='   ')
        print(wrapped_text)

        print("\n" + "-" * 80)

# Your original code with LLM explanations:
filters = {
    'variety': "Red Blend",
    'country': "US",
    'max_price': 100
}

query = "rich red wine with notes of cherry and chocolate"

filtered_results = retriever.search_by_filters(
    query=query,
    variety=filters['variety'],
    country=filters['country'],
    max_price=filters['max_price'],
    top_k=3
)

print_filtered_recommendations_with_explanations(query, filtered_results, filters)

class WineRecommender:
    def __init__(self, retriever):
        self.retriever = retriever
        self.user_favorites = []

    def display_wine_catalog(self, num_wines=20):
        """Display a catalog of wines for selection"""
        print("🍷 Wine Catalog (first {} wines):".format(num_wines))
        print("=" * 80)

        for i in range(min(num_wines, len(self.retriever.df))):
            wine = self.retriever.df.iloc[i]
            print(f"{i+1}. {wine.get('title', 'No title')}")
            print(f"   📍 {wine.get('variety', 'N/A')} | 🌍 {wine.get('country', 'N/A')} | 💰 ${wine.get('price', 'N/A')}")
            if pd.notna(wine.get('description')):
                desc = str(wine['description'])[:100] + "..." if len(str(wine['description'])) > 100 else wine['description']
                print(f"   📝 {desc}")
            print()

    def add_favorite_wines(self, wine_indices):
        """Add wines to user's favorites list"""
        for idx in wine_indices:
            if 0 <= idx < len(self.retriever.df):
                wine = self.retriever.df.iloc[idx].to_dict()
                if wine not in self.user_favorites:
                    self.user_favorites.append(wine)
                    print(f"✅ Added: {wine.get('title')}")
            else:
                print(f"❌ Wine with index {idx} not found")

    def get_favorites_profile(self):
        """Create a semantic profile of user's favorite wines"""
        if not self.user_favorites:
            return ""

        profile_parts = []
        for wine in self.user_favorites:
            wine_features = []
            if wine.get('variety'): wine_features.append(wine['variety'])
            if wine.get('country'): wine_features.append(wine['country'])
            if wine.get('region_1'): wine_features.append(wine['region_1'])
            if wine.get('description'):
                wine_features.append(wine['description'][:150])

            profile_parts.append(f"{wine.get('title', 'Unknown wine')} ({', '.join(wine_features)})")

        return "User likes wines with characteristics similar to: " + "; ".join(profile_parts)

    def get_similar_recommendations(self, top_k=10):
        """Generate recommendations based on user's favorite wines"""
        if not self.user_favorites:
            print("❌ Please add some favorite wines first!")
            return []

        print("\n🎯 Recommendations based on your preferences:")
        print("=" * 80)

        # Get recommendations based on all favorite wines
        all_recommendations = []
        for favorite in self.user_favorites:
            favorite_description = self._create_wine_description_from_dict(favorite)
            similar_wines = self.retriever.retrieve(favorite_description, top_k=top_k*3)

            # Exclude the favorite wines themselves from recommendations
            similar_wines = [w for w in similar_wines if w.get('title') != favorite.get('title')]
            all_recommendations.extend(similar_wines)

        # Remove duplicates and keep highest similarity scores
        unique_recommendations = {}
        for wine in all_recommendations:
            title = wine.get('title')
            if title not in unique_recommendations or wine['similarity_score'] > unique_recommendations[title]['similarity_score']:
                unique_recommendations[title] = wine

        # Get top-K recommendations
        final_recommendations = sorted(unique_recommendations.values(),
                                     key=lambda x: x['similarity_score'], reverse=True)[:top_k]

        return final_recommendations

    def _create_wine_description_from_dict(self, wine_dict):
        """Create a text description from wine dictionary"""
        desc_parts = []

        if wine_dict.get('title'):
            desc_parts.append(f"Wine: {wine_dict['title']}")

        if wine_dict.get('variety'):
            desc_parts.append(f"Variety: {wine_dict['variety']}")

        if wine_dict.get('country'):
            desc_parts.append(f"Country: {wine_dict['country']}")

        if wine_dict.get('region_1'):
            desc_parts.append(f"Region: {wine_dict['region_1']}")

        if wine_dict.get('description'):
            desc_parts.append(f"Description: {wine_dict['description']}")

        return ". ".join(desc_parts)

    def display_recommendations(self, recommendations):
        """Display recommendations with LLM explanations"""
        if not recommendations:
            print("😞 No suitable recommendations found")
            return

        for i, wine in enumerate(recommendations, 1):
            print(f"\n{i}. 🍷 {wine.get('title', 'No title')}")
            print(f"   📍 Variety: {wine.get('variety', 'N/A')}")
            print(f"   🌍 Country: {wine.get('country', 'N/A')}")
            print(f"   💰 Price: ${wine.get('price', 'N/A')}")
            print(f"   ⭐ Similarity: {wine['similarity_score']:.3f}")

            # Generate explanation based on user's favorites
            favorite_titles = [f["title"] for f in self.user_favorites if f.get('title')]
            explanation_query = f"wines similar to {', '.join(favorite_titles[:2])}"

            print(f"\n   💡 Why we recommend this:")
            explanation = generate_explanation(explanation_query, wine, wine['similarity_score'])

            # Format text with proper wrapping
            import textwrap
            wrapped_text = textwrap.fill(explanation, width=70, initial_indent='   ', subsequent_indent='   ')
            print(wrapped_text)

            print("\n" + "-" * 80)

def interactive_wine_recommendation_system():
    """Interactive wine recommendation system"""

    # Initialize the recommender
    recommender = WineRecommender(retriever)

    print("🎉 Welcome to the Wine Recommendation System!")
    print("Select wines you like, and we'll find similar ones for you!\n")

    while True:
        print("\n" + "=" * 60)
        print("1. 📋 Display Wine Catalog")
        print("2. ❤️  Add Favorite Wines")
        print("3. 👀 Show My Favorites")
        print("4. 🎯 Get Recommendations")
        print("5. 🚪 Exit")
        print("=" * 60)

        choice = input("\nSelect an option (1-5): ").strip()

        if choice == '1':
            # Display catalog
            print("\nLoading wine catalog...")
            recommender.display_wine_catalog(15)

        elif choice == '2':
            # Add favorite wines
            try:
                print("\nEnter the numbers of wines you like (e.g., 1, 3, 5)")
                indices_input = input("Wine numbers: ")
                indices = [int(idx.strip()) - 1 for idx in indices_input.split(',')]
                recommender.add_favorite_wines(indices)
            except ValueError:
                print("❌ Please enter valid numbers separated by commas")

        elif choice == '3':
            # Show current favorites
            if recommender.user_favorites:
                print("\n❤️ Your Favorite Wines:")
                for i, wine in enumerate(recommender.user_favorites, 1):
                    print(f"{i}. {wine.get('title')} - {wine.get('variety')} from {wine.get('country')}")
            else:
                print("❌ You haven't added any favorite wines yet")

        elif choice == '4':
            # Get recommendations
            if not recommender.user_favorites:
                print("❌ Please add some favorite wines first!")
                continue

            try:
                num_recs = input("How many recommendations? (default: 5): ").strip()
                num_recs = int(num_recs) if num_recs else 5

                print("\n🔍 Finding recommendations based on your favorites...")
                recommendations = recommender.get_similar_recommendations(top_k=num_recs)
                recommender.display_recommendations(recommendations)

            except ValueError:
                print("❌ Please enter a valid number")

        elif choice == '5':
            print("👋 Thank you for using our recommendation system!")
            break

        else:
            print("❌ Invalid choice, please try again")

# Initialize and run the system
print("Initializing Wine Recommendation System...")
recommender_system = WineRecommender(retriever)

# Run the interactive system
interactive_wine_recommendation_system()